const lucky = [
  {
    id: "1",
    name: "封印嗒妮小姐卡片",
    date: "2020/08/16",
    photo: "https://i.imgur.com/KHbnAdj.png",
  },
  {
    id: "2",
    name: "封印嗒妮小姐卡片",
    date: "2020/08/17",
    photo: "https://i.imgur.com/TjEhxfZ.png",
  },
  {
    id: "3",
    name: "席琳基米卡片",
    date: "2020/08/19",
    photo: "https://i.imgur.com/TFYcKzL.png",
  },
  {
    id: "4",
    name: "封印冰晶龍卡片",
    date: "2020/08/20",
    photo: "https://i.imgur.com/TSxKD3w.png",
  },
  {
    id: "5",
    name: "米古爾卡片",
    date: "2020/08/20",
    photo: "https://i.imgur.com/lk8WrsD.png",
  },
  {
    id: "6",
    name: "封印喬伊亞卡片",
    date: "2020/08/20",
    photo: "https://i.imgur.com/YcONAgD.png",
  },
  {
    id: "7",
    name: "黃金蟲卡片",
    date: "2020/08/21",
    photo: "https://i.imgur.com/e8uWCUD.png",
  },
  {
    id: "8",
    name: "魔劍士達納托斯的記憶卡片",
    date: "2020/08/21",
    photo: "https://i.imgur.com/r8ZcQSk.png",
  },
  {
    id: "9",
    name: "蜂后卡片",
    date: "2020/08/21",
    photo: "https://i.imgur.com/5PGL95O.png",
  },
  {
    id: "10",
    name: "蟻后卡片",
    date: "2020/08/21",
    photo: "https://i.imgur.com/gyKsCK9.png",
  },
  {
    id: "11",
    name: "封印闇●神官瑪嘉雷特卡片卡片",
    date: "2020/08/21",
    photo: "https://i.imgur.com/D3W3hxW.png",
  },
  {
    id: "12",
    name: "魔劍士達納托斯的記憶卡片",
    date: "2020/08/22",
    photo: "https://i.imgur.com/7U2BQ8x.png",
  },
  {
    id: "13",
    name: "封印黑暗之王卡片",
    date: "2020/08/22",
    photo: "https://i.imgur.com/1JWkDiq.png",
  },
  {
    id: "14",
    name: "米古爾卡片",
    date: "2020/08/22",
    photo: "https://i.imgur.com/SZ1lSdS.png",
  },
  {
    id: "15",
    name: "封印闇●創造者普拉梅姆卡片",
    date: "2020/08/23",
    photo: "https://i.imgur.com/tfE1Hlc.png",
  },
  {
    id: "16",
    name: "封印魔劍士達納托斯的記憶卡片",
    date: "2020/08/24",
    photo: "https://i.imgur.com/WSzvrDc.png",
  },
  {
    id: "17",
    name: "魔劍士達納托斯的記憶卡片",
    date: "2020/08/25",
    photo: "https://i.imgur.com/amoyHbe.png",
  },
  {
    id: "18",
    name: "封印幽暗夢魘卡片",
    date: "2020/08/25",
    photo: "https://i.imgur.com/BpDX4xq.png",
  },
  {
    id: "19",
    name: "封印月夜貓卡片",
    date: "2020/08/25",
    photo: "https://i.imgur.com/8bFgyrx.png",
  },
  {
    id: "20",
    name: "封印時間支配者卡片",
    date: "2020/08/25",
    photo: "https://i.imgur.com/9P7HbRF.png",
  },
  {
    id: "21",
    name: "黃金蟲卡片",
    date: "2020/08/25",
    photo: "https://i.imgur.com/ofNj4i7.png",
  },
];
